projects:
  vipinvoicesdatahandler:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        maxDepth: 3
  vipinvoices:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
